### ISSUE TITLE
Simplify CollectionChange

### ISSUE THREAD

**Issue by neilpa** [gitdoapp/RAC-MutableCollectionProperty#1]
All you need is insert and remove with element and index. Move, replace, etc. are just composites and can be defined in those terms.

```swift
enum CollectionChange<T> {
    case Insert(T, Int)
    case Remove(T, Int)
    case Composite([CollectionChange])
}
```

c.f. ReactiveCocoa/ReactiveCocoa#2485

**Comment by pepibumur** [comment]
Thanks @neilpa :), have a question about your Composite event, what is it supposed to be fore?
I have also some doubts regarding the access to the array from multiple threads because I used the `NSRecursiveLock` similar to what the `NSMutableProperty` does but I'm not sure if this is helping in this is case to avoid simultaneous access from different threads.

**Comment by neilpa** [comment]
> question about your Composite event, what is it supposed to be fore?

It makes it easier to re-identify move, replace, etc. events. This way you don't have to buffer multiple inserts and removes creating animations without having to buffer multiple inserts/removes. This is easier to explain with code that I'll try to show today.

> I have also some doubts regarding the access to the array from multiple threads because I used the NSRecursiveLock similar to what the NSMutableProperty does but I'm not sure if this is helping in this is case to avoid simultaneous access from different threads.

Yea, this is going to be a problem if the goal is creating a data source for a table or collection view. The  `MutableProperty` isn't going to help you since there's no way to coordinate updates safely if the collection is animating while an update happens underneath you.

I've tried to make shared data stores work in other projects/languages. Each time I hit the above bug and fell back to a copy for the UI. It's simpler and can be driven by events from the original source

Generally, this is a much harder problem than most people give it credit for. I've got a private repo where I was experimenting with stuff like this. I opened neilpa/Rex#51 to migrate it to my public repo for RAC experiments.

**Comment by pepibumur** [comment]
> It makes it easier to re-identify move, replace, etc. events. This way you don't have to buffer multiple inserts and removes creating animations without having to buffer multiple inserts/removes. This is easier to explain with code that I'll try to show today.

Nice, thanks so much, I'll refactor the implementation to use these events instead.

> Yea, this is a problem if the goal is a data source for a table or collection view. MutableProperty isn't going to help since there's no way to coordinate updates during animations. You'll inevitably hit a case where the collection changes while the view is animating and crash.

Yes!, well known problem creating inconsistence between Collection <~> View that we always end up solving using the `reloadData()` or equivalent command on the view to use the entire collection instead. Sounds great, I'm using your repository in some projects, think the extensions you're adding there are very useful. I tried to do something similar to get `NoError` signals from an `Error` signals :P

**Comment by pepibumur** [comment]
@neilpa done here https://github.com/gitdoapp/RAC-MutableCollectionProperty/pull/2

**Comment by andykog** [comment]
Is there any reason not to leave `.Replace ` change type? It's handy when displaying data inside `UITableView`. Applying `.Insert` and `.Remove` breaks animation.

**Comment by pepibumur** [comment]
Mmm just for simplicity @andykog . What we could do instead is grouping events that are related on a `.Composite` event type. And from the observer point of view, if there's a `.Delete` and `.Insert` treat it as an update.

**Comment by andykog** [comment]
Yes, I understand, that we replaced `.Replace` with `.Remove` + `.Insert`, but at this point its problematic to represent and consume batch of changes, for example, how should we represent update of elements 0 and 1? I see possibilities:
* `.Composite([ .Remove(0), .Insert(0), .Remove(1), .Insert(1) ])`
* `.Composite([ .Remove(0), .Remove(0), .Insert(1), .Insert(1) ])`
* `.Composite([ .Composite([ .Remove(0), .Insert(0) ]), Composite([ .Remove(1), .Insert(1) ]) ])`

And it's really hard for consumer to parse those combinations to detect updates

**Comment by pepibumur** [comment]
You're right @andykog, we could reintroduce the `.Update` event type. I can tackle it, what do you think?

**Comment by andykog** [comment]
Basically, I've made it in #10, just wanted to know your attitude

**Comment by pepibumur** [comment]
:+1: from my side @andykog
