### ISSUE TITLE
Changes Producer

### ISSUE THREAD

**Issue by andersio** [gitdoapp/RAC-MutableCollectionProperty#3]
https://github.com/gitdoapp/RAC-MutableCollectionProperty/blob/master/MutableCollectionProperty/MutableCollectionProperty.swift#L60

I wonder if the latest change event has to be buffered. With only one observer it has no problem. However, when you have a second observer to the collection, starting the changes producer would replay the cached, latest change event, while the second observer should have already seen the latest version of the collection.

Hadn't this better be a `Signal`?

**Comment by pepibumur** [comment]
Agree, another option would be to set the buffer to 0. That way if there's another subscriber that wouldn't receive the previous change.
Another option would be to expose publicly a subscription method and for new subscribers send always a first event which is: "this is the current collection status". What do you think?

**Comment by andersio** [comment]
Are you meant to make it thread safe?

**Comment by pepibumur** [comment]
It's currently using NSRecursiveLock to avoid problems with multiple threat accessing it.
